export default {
    DEBUG: true,
    DISPLAY_HELPERS: false,
    LIGHT_COLOR: 0xF9FAFC,
    DARK_COLOR: 0x1A1C21,
    PADDLE_DEPTH: 4,
    PLAYINGFIELD_WIDTH: 100,
    PLAYINGFIELD_DEPTH: 75,
    GYRO_CONTROLLER_SENSITIVITY: 3,
    TOUCH_CONTROLLER_SENSITIVITY: 1.5
}